name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.11
            2.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Build using make
        run: |
          VERSION_ID=${{ github.ref }} make

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          name: swix
          asset_path: ./promtail-${{ github.ref }}.swix
          asset_name: promtail-${{ github.ref }}.swix
          asset_type: application/octet-stream